# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshc < Formula
  desc "A powerful SSH client for the terminal"
  homepage "https://github.com/xvertile/sshc"
  version "1.0.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.23/sshc_1.0.23_darwin_amd64.tar.gz"
      sha256 "777bf097dff432efa1e5ed5c649750231cfe5153d28aba4beb1321086a71dbcd"

      def install
        bin.install "sshc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.23/sshc_1.0.23_darwin_arm64.tar.gz"
      sha256 "c00c8dc312ef4a85a70237a4ce9ba1903b6ab53e89d7203ff20f76b369cde43f"

      def install
        bin.install "sshc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.23/sshc_1.0.23_linux_amd64.tar.gz"
      sha256 "45441ec3b2f6df17e8964c40856a086d014bb43901c4ac175bc341ed2dda9535"
      def install
        bin.install "sshc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.23/sshc_1.0.23_linux_arm64.tar.gz"
      sha256 "a4f06b7ddba42623f28bfa5e64058da38d388bab270f6f56efe4c1344870064a"
      def install
        bin.install "sshc"
      end
    end
  end

  test do
    system "#{bin}/sshc --version"
  end
end
