# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshc < Formula
  desc "A powerful SSH client for the terminal"
  homepage "https://github.com/xvertile/sshc"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.0/sshc_1.0.0_darwin_amd64.tar.gz"
      sha256 "b894e73f76b366a6e1135fe1d2abb73bb668fe84ed651d4803f707538127f6ce"

      def install
        bin.install "sshc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.0/sshc_1.0.0_darwin_arm64.tar.gz"
      sha256 "6a61b772724c32d59fc4b8aa18462cc1f9afcbc0ff6d0aeecf53e4f1c23f6f3d"

      def install
        bin.install "sshc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.0/sshc_1.0.0_linux_amd64.tar.gz"
      sha256 "e6b3fa674b45ede47d36a6f5a25bda607f53af5f5f6d0ce70076de1f99f91fb8"
      def install
        bin.install "sshc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvertile/sshc/releases/download/v1.0.0/sshc_1.0.0_linux_arm64.tar.gz"
      sha256 "2493b50d1b8801386bb00cf15d8a6c8db53264ab814305d57aca9685b12ecf59"
      def install
        bin.install "sshc"
      end
    end
  end

  test do
    system "#{bin}/sshc --version"
  end
end
